### ISSUE TITLE
Run mothur tools with docker_enabled

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#1484]
need to test whether this entry in tpv/tools.yml will work for all mothur tools including ones with specific entries. This will protect user data from large files created in error.

```
  toolshed.g2.bx.psu.edu/repos/iuc/mothur.*:
    params:
      docker_enabled: true
      docker_run_extra_arguments: --pids-limit 10000 --ulimit fsize=1000000000 --env TERM=vt100
```
