### ISSUE TITLE
dependency resolvers conf sample file will disappear in 21.09

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/infrastructure#512]
this file will disappear from galaxy, it needs to be copied to files/galaxy/config in this repo
https://github.com/galaxyproject/galaxy/blob/release_21.05/lib/galaxy/config/sample/dependency_resolvers_conf.xml.sample

**Comment by cat-bro** [comment]
or it can be a variable in galaxy_config.galaxy 

default is
```
galaxy:
  dependency_resolvers:
    - type: tool_shed_packages
    - type: galaxy_packages
    - type: conda
    - type: galaxy_packages
      versionless: true
    - type: conda
      versionless: true
```


https://docs.galaxyproject.org/en/master/admin/dependency_resolvers.html
